[project]
name = "audio-to-text"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Joao Marcos Visotaky Junior", email = "admin@palantirdatasolutions.com"},
]
dependencies = ["fastapi>=0.116.1", "openai>=1.101.0", "slowapi>=0.1.9"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
